### PR TITLE
Add this readme.md files by Soumik Baithalu

### PR DESCRIPTION
**Pull request by soumik2012**
Add my file for this hacktoberfest, created readme.md

### CODE REVIEW

**Review by PriyanshTri — CHANGES_REQUESTED** [review]
Improve a typo at line 11

**Comment by PriyanshTri** [comment]
1 space is needed between 'bootstrapped with' in  line 11

**Comment by soumik2012** [comment]
> Improve a typo at line 11
 what do want to add in typo ex("emoji ')

**Comment by PriyanshTri** [comment]
Two words has been combined together. There is lack of a space in line 11 between bootstrapped and with

**Comment by soumik2012** [comment]
> Two words has been combined together. There is lack of a space in line 11 between bootstrapped and with

i have request could please add lable of hacktoberfest it will help me to grow my PR please humble request

**Comment by PriyanshTri** [comment]
Thanks for your contribution. Happy hacktoberfest 2020 🎉

**Comment by PriyanshTri** [comment]
Create a PR for the contribution page.

**Comment by soumik2012** [comment]
Thank you very much

**Pull request merged**
