### PR TITLE
Layout made with some styling

### PR DESCRIPTION
**Pull request by Abhiramborige**
Used bootstrap framework.
Small simple styling made
HTML Layout completed

### CODE REVIEW

**Comment by Abhiramborige** [comment]
Please merge if you like the contribution

**Comment by PriyanshTri** [comment]
remove the body keyword in the top of the page with h2 tag and same goes to footer keyword in the bottom

**Comment by Abhiramborige** [comment]
Yeah ok i will try

**Comment by Abhiramborige** [comment]
So i have to remove body and footer headings or the whole section??

**Comment by PriyanshTri** [comment]
You need to remove the body and footer keyword in H2 tag.

**Comment by Abhiramborige** [comment]
Okay

**Comment by Abhiramborige** [comment]
Hey!. Some modifications are done. Please look into it!!

**Comment by Abhiramborige** [comment]
Hey can u please add hactoberfest-accepted label according to the guidlines

**Comment by Abhiramborige** [comment]
Please 🙏🤝

**Comment by PriyanshTri** [comment]
done

**Pull request merged**
